-- Give the imported tables a generated id.
--
-- The Milestone 1 importer supplied `id` by hand from the legacy JSON, so
-- `club_reviews.id` and `clubs.id` were left with no identity and no default.
-- That was invisible while only the importer wrote to them. It stops being
-- invisible the moment a member writes a review: the insert has to name its own
-- primary key, which a browser cannot be trusted to do and which collides on
-- the second concurrent write.
--
-- `profiles.id` is deliberately left alone — it is a uuid that references
-- auth.users, and generating one there would break the link.
--
-- `by default`, not `always`: the importer still needs to be able to supply an
-- id when re-running against legacy data.

alter table public.club_reviews
  alter column id add generated by default as identity;

alter table public.clubs
  alter column id add generated by default as identity;

-- Start each sequence above whatever the import already used, or the first
-- insert would collide with row 1.
select setval(pg_get_serial_sequence('public.club_reviews', 'id'),
              coalesce((select max(id) from public.club_reviews), 0) + 1, false);

select setval(pg_get_serial_sequence('public.clubs', 'id'),
              coalesce((select max(id) from public.clubs), 0) + 1, false);
